blacklist:
- mckinnc_ekf
- ls_slam
- resilient_debug_gui
- zed_ar_track_alvar_example
- zed_depth_sub_tutorial
- zed_display_rviz
- zed_nodelet_example
- zed_ros
- zed_rtabmap_example
- zed_tracking_sub_tutorial
- zed_video_sub_tutorial
- zed_wrapper
build_space: build
catkin_make_args: []
cmake_args:
- -DCMAKE_EXPORT_COMPILE_COMMANDS=ON
- -DCMAKE_BUILD_TYPE=Debug
devel_layout: linked
devel_space: devel
extend_path: null
install: false
install_space: install
isolate_install: false
jobs_args: []
log_space: logs
make_args: []
source_space: src
use_env_cache: false
use_internal_make_jobserver: true
whitelist: []
